// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: clock.sql

package sqlcgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getClockOverride = `-- name: GetClockOverride :one
SELECT override_now
FROM app_clock
WHERE singleton = TRUE
`

func (q *Queries) GetClockOverride(ctx context.Context) (pgtype.Timestamptz, error) {
	row := q.db.QueryRow(ctx, getClockOverride)
	var override_now pgtype.Timestamptz
	err := row.Scan(&override_now)
	return override_now, err
}

const setClockOverride = `-- name: SetClockOverride :exec
UPDATE app_clock
SET override_now = $1, updated_at = NOW()
WHERE singleton = TRUE
`

func (q *Queries) SetClockOverride(ctx context.Context, overrideNow pgtype.Timestamptz) error {
	_, err := q.db.Exec(ctx, setClockOverride, overrideNow)
	return err
}
