// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: digests.sql

package sqlcgen

import (
	"context"
)

const createDigestMessage = `-- name: CreateDigestMessage :execrows
INSERT INTO digest_messages (user_id, telegram_message_id, state, product_ids)
VALUES ($1, $2, 'active', $3)
`

type CreateDigestMessageParams struct {
	UserID            int64
	TelegramMessageID int64
	ProductIds        []byte
}

func (q *Queries) CreateDigestMessage(ctx context.Context, arg CreateDigestMessageParams) (int64, error) {
	result, err := q.db.Exec(ctx, createDigestMessage, arg.UserID, arg.TelegramMessageID, arg.ProductIds)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const listActiveDigestMessages = `-- name: ListActiveDigestMessages :many
SELECT id, user_id, telegram_message_id, state, product_ids, created_at, updated_at
FROM digest_messages
WHERE state = 'active'
`

func (q *Queries) ListActiveDigestMessages(ctx context.Context) ([]DigestMessage, error) {
	rows, err := q.db.Query(ctx, listActiveDigestMessages)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []DigestMessage
	for rows.Next() {
		var i DigestMessage
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.TelegramMessageID,
			&i.State,
			&i.ProductIds,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markDigestDeleted = `-- name: MarkDigestDeleted :exec
UPDATE digest_messages
SET state = 'deleted', updated_at = NOW()
WHERE id = $1
`

func (q *Queries) MarkDigestDeleted(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, markDigestDeleted, id)
	return err
}
