// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: drafts.sql

package sqlcgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const applyDraftAIReviewIfReady = `-- name: ApplyDraftAIReviewIfReady :execrows
UPDATE draft_sessions
SET draft_name = $2,
    draft_expires_on = $3,
    raw_deadline_phrase = $4,
    draft_payload = $5,
    updated_at = NOW()
WHERE id = $1
  AND status = 'ready'
`

type ApplyDraftAIReviewIfReadyParams struct {
	ID                int64
	DraftName         *string
	DraftExpiresOn    pgtype.Date
	RawDeadlinePhrase *string
	DraftPayload      []byte
}

func (q *Queries) ApplyDraftAIReviewIfReady(ctx context.Context, arg ApplyDraftAIReviewIfReadyParams) (int64, error) {
	result, err := q.db.Exec(ctx, applyDraftAIReviewIfReady,
		arg.ID,
		arg.DraftName,
		arg.DraftExpiresOn,
		arg.RawDeadlinePhrase,
		arg.DraftPayload,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const createDraftSession = `-- name: CreateDraftSession :one
INSERT INTO draft_sessions (
    trace_id, user_id, chat_id, source_kind, status, source_message_id, feedback_message_id,
    draft_name, draft_expires_on, raw_deadline_phrase, draft_payload, cleanup_after
)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12)
RETURNING id
`

type CreateDraftSessionParams struct {
	TraceID           string
	UserID            int64
	ChatID            int64
	SourceKind        string
	Status            string
	SourceMessageID   *int64
	FeedbackMessageID *int64
	DraftName         *string
	DraftExpiresOn    pgtype.Date
	RawDeadlinePhrase *string
	DraftPayload      []byte
	CleanupAfter      pgtype.Timestamptz
}

func (q *Queries) CreateDraftSession(ctx context.Context, arg CreateDraftSessionParams) (int64, error) {
	row := q.db.QueryRow(ctx, createDraftSession,
		arg.TraceID,
		arg.UserID,
		arg.ChatID,
		arg.SourceKind,
		arg.Status,
		arg.SourceMessageID,
		arg.FeedbackMessageID,
		arg.DraftName,
		arg.DraftExpiresOn,
		arg.RawDeadlinePhrase,
		arg.DraftPayload,
		arg.CleanupAfter,
	)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const getDraftSession = `-- name: GetDraftSession :one
SELECT id, trace_id, user_id, chat_id, source_kind, status, source_message_id, draft_message_id, feedback_message_id,
       draft_name, draft_expires_on, raw_deadline_phrase, draft_payload, cleanup_after, created_at, updated_at,
       confirmed_product_id, edit_prompt_message_id
FROM draft_sessions
WHERE id = $1
`

func (q *Queries) GetDraftSession(ctx context.Context, id int64) (DraftSession, error) {
	row := q.db.QueryRow(ctx, getDraftSession, id)
	var i DraftSession
	err := row.Scan(
		&i.ID,
		&i.TraceID,
		&i.UserID,
		&i.ChatID,
		&i.SourceKind,
		&i.Status,
		&i.SourceMessageID,
		&i.DraftMessageID,
		&i.FeedbackMessageID,
		&i.DraftName,
		&i.DraftExpiresOn,
		&i.RawDeadlinePhrase,
		&i.DraftPayload,
		&i.CleanupAfter,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ConfirmedProductID,
		&i.EditPromptMessageID,
	)
	return i, err
}

const getDraftSessionByTraceID = `-- name: GetDraftSessionByTraceID :one
SELECT id, trace_id, user_id, chat_id, source_kind, status, source_message_id, draft_message_id, feedback_message_id,
       draft_name, draft_expires_on, raw_deadline_phrase, draft_payload, cleanup_after, created_at, updated_at,
       confirmed_product_id, edit_prompt_message_id
FROM draft_sessions
WHERE trace_id = $1
ORDER BY created_at DESC
LIMIT 1
`

func (q *Queries) GetDraftSessionByTraceID(ctx context.Context, traceID string) (DraftSession, error) {
	row := q.db.QueryRow(ctx, getDraftSessionByTraceID, traceID)
	var i DraftSession
	err := row.Scan(
		&i.ID,
		&i.TraceID,
		&i.UserID,
		&i.ChatID,
		&i.SourceKind,
		&i.Status,
		&i.SourceMessageID,
		&i.DraftMessageID,
		&i.FeedbackMessageID,
		&i.DraftName,
		&i.DraftExpiresOn,
		&i.RawDeadlinePhrase,
		&i.DraftPayload,
		&i.CleanupAfter,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ConfirmedProductID,
		&i.EditPromptMessageID,
	)
	return i, err
}

const getEditableDraftSessionForUser = `-- name: GetEditableDraftSessionForUser :one
SELECT id, trace_id, user_id, chat_id, source_kind, status, source_message_id, draft_message_id, feedback_message_id,
       draft_name, draft_expires_on, raw_deadline_phrase, draft_payload, cleanup_after, created_at, updated_at,
       confirmed_product_id, edit_prompt_message_id
FROM draft_sessions
WHERE user_id = $1 AND status IN ('editing_name', 'editing_date')
ORDER BY updated_at DESC
LIMIT 1
`

func (q *Queries) GetEditableDraftSessionForUser(ctx context.Context, userID int64) (DraftSession, error) {
	row := q.db.QueryRow(ctx, getEditableDraftSessionForUser, userID)
	var i DraftSession
	err := row.Scan(
		&i.ID,
		&i.TraceID,
		&i.UserID,
		&i.ChatID,
		&i.SourceKind,
		&i.Status,
		&i.SourceMessageID,
		&i.DraftMessageID,
		&i.FeedbackMessageID,
		&i.DraftName,
		&i.DraftExpiresOn,
		&i.RawDeadlinePhrase,
		&i.DraftPayload,
		&i.CleanupAfter,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ConfirmedProductID,
		&i.EditPromptMessageID,
	)
	return i, err
}

const listStaleDraftSessions = `-- name: ListStaleDraftSessions :many
SELECT id, trace_id, user_id, chat_id, source_kind, status, source_message_id, draft_message_id, feedback_message_id,
       draft_name, draft_expires_on, raw_deadline_phrase, draft_payload, cleanup_after, created_at, updated_at,
       confirmed_product_id, edit_prompt_message_id
FROM draft_sessions
WHERE status IN ('ready', 'editing_name', 'editing_date')
  AND created_at <= $1
ORDER BY created_at ASC
`

func (q *Queries) ListStaleDraftSessions(ctx context.Context, createdAt pgtype.Timestamptz) ([]DraftSession, error) {
	rows, err := q.db.Query(ctx, listStaleDraftSessions, createdAt)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []DraftSession
	for rows.Next() {
		var i DraftSession
		if err := rows.Scan(
			&i.ID,
			&i.TraceID,
			&i.UserID,
			&i.ChatID,
			&i.SourceKind,
			&i.Status,
			&i.SourceMessageID,
			&i.DraftMessageID,
			&i.FeedbackMessageID,
			&i.DraftName,
			&i.DraftExpiresOn,
			&i.RawDeadlinePhrase,
			&i.DraftPayload,
			&i.CleanupAfter,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.ConfirmedProductID,
			&i.EditPromptMessageID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const lockDraftForConfirmation = `-- name: LockDraftForConfirmation :one
SELECT id, trace_id, user_id, chat_id, source_kind, status, source_message_id, draft_message_id, feedback_message_id,
       draft_name, draft_expires_on, raw_deadline_phrase, draft_payload, cleanup_after, created_at, updated_at,
       confirmed_product_id, edit_prompt_message_id
FROM draft_sessions
WHERE id = $1
FOR UPDATE
`

func (q *Queries) LockDraftForConfirmation(ctx context.Context, id int64) (DraftSession, error) {
	row := q.db.QueryRow(ctx, lockDraftForConfirmation, id)
	var i DraftSession
	err := row.Scan(
		&i.ID,
		&i.TraceID,
		&i.UserID,
		&i.ChatID,
		&i.SourceKind,
		&i.Status,
		&i.SourceMessageID,
		&i.DraftMessageID,
		&i.FeedbackMessageID,
		&i.DraftName,
		&i.DraftExpiresOn,
		&i.RawDeadlinePhrase,
		&i.DraftPayload,
		&i.CleanupAfter,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ConfirmedProductID,
		&i.EditPromptMessageID,
	)
	return i, err
}

const markDraftConfirmed = `-- name: MarkDraftConfirmed :exec
UPDATE draft_sessions
SET status = $2,
    confirmed_product_id = $3,
    edit_prompt_message_id = NULL,
    updated_at = NOW()
WHERE id = $1
`

type MarkDraftConfirmedParams struct {
	ID                 int64
	Status             string
	ConfirmedProductID *int64
}

func (q *Queries) MarkDraftConfirmed(ctx context.Context, arg MarkDraftConfirmedParams) error {
	_, err := q.db.Exec(ctx, markDraftConfirmed, arg.ID, arg.Status, arg.ConfirmedProductID)
	return err
}

const setDraftEditPromptMessageID = `-- name: SetDraftEditPromptMessageID :exec
UPDATE draft_sessions
SET edit_prompt_message_id = $2, updated_at = NOW()
WHERE id = $1
`

type SetDraftEditPromptMessageIDParams struct {
	ID                  int64
	EditPromptMessageID *int64
}

func (q *Queries) SetDraftEditPromptMessageID(ctx context.Context, arg SetDraftEditPromptMessageIDParams) error {
	_, err := q.db.Exec(ctx, setDraftEditPromptMessageID, arg.ID, arg.EditPromptMessageID)
	return err
}

const setDraftMessageID = `-- name: SetDraftMessageID :exec
UPDATE draft_sessions
SET draft_message_id = $2, updated_at = NOW()
WHERE id = $1
`

type SetDraftMessageIDParams struct {
	ID             int64
	DraftMessageID *int64
}

func (q *Queries) SetDraftMessageID(ctx context.Context, arg SetDraftMessageIDParams) error {
	_, err := q.db.Exec(ctx, setDraftMessageID, arg.ID, arg.DraftMessageID)
	return err
}

const updateDraftFields = `-- name: UpdateDraftFields :exec
UPDATE draft_sessions
SET draft_name = $2,
    draft_expires_on = $3,
    raw_deadline_phrase = $4,
    status = $5,
    edit_prompt_message_id = CASE
        WHEN $5 = 'ready' THEN NULL
        ELSE edit_prompt_message_id
    END,
    updated_at = NOW()
WHERE id = $1
`

type UpdateDraftFieldsParams struct {
	ID                int64
	DraftName         *string
	DraftExpiresOn    pgtype.Date
	RawDeadlinePhrase *string
	Status            string
}

func (q *Queries) UpdateDraftFields(ctx context.Context, arg UpdateDraftFieldsParams) error {
	_, err := q.db.Exec(ctx, updateDraftFields,
		arg.ID,
		arg.DraftName,
		arg.DraftExpiresOn,
		arg.RawDeadlinePhrase,
		arg.Status,
	)
	return err
}

const updateDraftPayload = `-- name: UpdateDraftPayload :exec
UPDATE draft_sessions
SET draft_payload = $2,
    updated_at = NOW()
WHERE id = $1
`

type UpdateDraftPayloadParams struct {
	ID           int64
	DraftPayload []byte
}

func (q *Queries) UpdateDraftPayload(ctx context.Context, arg UpdateDraftPayloadParams) error {
	_, err := q.db.Exec(ctx, updateDraftPayload, arg.ID, arg.DraftPayload)
	return err
}

const updateDraftStatus = `-- name: UpdateDraftStatus :exec
UPDATE draft_sessions
SET status = $2,
    edit_prompt_message_id = CASE
        WHEN $2 IN ('ready', 'confirmed', 'canceled', 'deleted', 'failed') THEN NULL
        ELSE edit_prompt_message_id
    END,
    updated_at = NOW()
WHERE id = $1
`

type UpdateDraftStatusParams struct {
	ID     int64
	Status string
}

func (q *Queries) UpdateDraftStatus(ctx context.Context, arg UpdateDraftStatusParams) error {
	_, err := q.db.Exec(ctx, updateDraftStatus, arg.ID, arg.Status)
	return err
}
