// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: e2e_reset.sql

package sqlcgen

import (
	"context"
)

const deleteDigestMessagesByUser = `-- name: DeleteDigestMessagesByUser :execrows
DELETE FROM digest_messages
WHERE user_id = $1
`

func (q *Queries) DeleteDigestMessagesByUser(ctx context.Context, userID int64) (int64, error) {
	result, err := q.db.Exec(ctx, deleteDigestMessagesByUser, userID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deleteDraftSessionsByUser = `-- name: DeleteDraftSessionsByUser :execrows
DELETE FROM draft_sessions
WHERE user_id = $1
`

func (q *Queries) DeleteDraftSessionsByUser(ctx context.Context, userID int64) (int64, error) {
	result, err := q.db.Exec(ctx, deleteDraftSessionsByUser, userID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deleteJobsForE2EUser = `-- name: DeleteJobsForE2EUser :execrows
DELETE FROM jobs
WHERE payload @> jsonb_build_object('user_id', to_jsonb($1::bigint))
   OR ($2::bigint <> 0 AND payload @> jsonb_build_object('chat_id', to_jsonb($2::bigint)))
`

type DeleteJobsForE2EUserParams struct {
	Column1 int64
	Column2 int64
}

func (q *Queries) DeleteJobsForE2EUser(ctx context.Context, arg DeleteJobsForE2EUserParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteJobsForE2EUser, arg.Column1, arg.Column2)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deleteProductsByUser = `-- name: DeleteProductsByUser :execrows
DELETE FROM products
WHERE user_id = $1
`

func (q *Queries) DeleteProductsByUser(ctx context.Context, userID int64) (int64, error) {
	result, err := q.db.Exec(ctx, deleteProductsByUser, userID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const listActiveDigestMessagesForUser = `-- name: ListActiveDigestMessagesForUser :many
SELECT id, user_id, telegram_message_id, state, product_ids, created_at, updated_at
FROM digest_messages
WHERE user_id = $1 AND state = 'active'
ORDER BY id ASC
`

func (q *Queries) ListActiveDigestMessagesForUser(ctx context.Context, userID int64) ([]DigestMessage, error) {
	rows, err := q.db.Query(ctx, listActiveDigestMessagesForUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []DigestMessage
	for rows.Next() {
		var i DigestMessage
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.TelegramMessageID,
			&i.State,
			&i.ProductIds,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listDraftSessionsForUser = `-- name: ListDraftSessionsForUser :many
SELECT id, trace_id, user_id, chat_id, source_kind, status, source_message_id, draft_message_id, feedback_message_id,
       draft_name, draft_expires_on, raw_deadline_phrase, draft_payload, cleanup_after, created_at, updated_at,
       confirmed_product_id, edit_prompt_message_id
FROM draft_sessions
WHERE user_id = $1
ORDER BY id ASC
`

func (q *Queries) ListDraftSessionsForUser(ctx context.Context, userID int64) ([]DraftSession, error) {
	rows, err := q.db.Query(ctx, listDraftSessionsForUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []DraftSession
	for rows.Next() {
		var i DraftSession
		if err := rows.Scan(
			&i.ID,
			&i.TraceID,
			&i.UserID,
			&i.ChatID,
			&i.SourceKind,
			&i.Status,
			&i.SourceMessageID,
			&i.DraftMessageID,
			&i.FeedbackMessageID,
			&i.DraftName,
			&i.DraftExpiresOn,
			&i.RawDeadlinePhrase,
			&i.DraftPayload,
			&i.CleanupAfter,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.ConfirmedProductID,
			&i.EditPromptMessageID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const resetUserSettingsForE2E = `-- name: ResetUserSettingsForE2E :exec
UPDATE user_settings
SET dashboard_message_id = NULL,
    timezone = $2,
    digest_local_time = $3,
    updated_at = NOW()
WHERE user_id = $1
`

type ResetUserSettingsForE2EParams struct {
	UserID          int64
	Timezone        string
	DigestLocalTime string
}

func (q *Queries) ResetUserSettingsForE2E(ctx context.Context, arg ResetUserSettingsForE2EParams) error {
	_, err := q.db.Exec(ctx, resetUserSettingsForE2E, arg.UserID, arg.Timezone, arg.DigestLocalTime)
	return err
}
