// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: ingest_events.sql

package sqlcgen

import (
	"context"
)

const createIngestEvent = `-- name: CreateIngestEvent :execrows
INSERT INTO ingest_events (trace_id, user_id, chat_id, message_id, message_kind, status, summary, metadata)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
`

type CreateIngestEventParams struct {
	TraceID     string
	UserID      *int64
	ChatID      *int64
	MessageID   *int64
	MessageKind string
	Status      string
	Summary     *string
	Metadata    []byte
}

func (q *Queries) CreateIngestEvent(ctx context.Context, arg CreateIngestEventParams) (int64, error) {
	result, err := q.db.Exec(ctx, createIngestEvent,
		arg.TraceID,
		arg.UserID,
		arg.ChatID,
		arg.MessageID,
		arg.MessageKind,
		arg.Status,
		arg.Summary,
		arg.Metadata,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const updateIngestStatus = `-- name: UpdateIngestStatus :exec
UPDATE ingest_events
SET status = $2, summary = $3, updated_at = NOW()
WHERE trace_id = $1
`

type UpdateIngestStatusParams struct {
	TraceID string
	Status  string
	Summary *string
}

func (q *Queries) UpdateIngestStatus(ctx context.Context, arg UpdateIngestStatusParams) error {
	_, err := q.db.Exec(ctx, updateIngestStatus, arg.TraceID, arg.Status, arg.Summary)
	return err
}
