// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: jobs.sql

package sqlcgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const claimJob = `-- name: ClaimJob :one
WITH next_job AS (
    SELECT jobs.id
    FROM jobs
    WHERE jobs.status IN ('queued', 'retry')
      AND jobs.run_at <= $1
      AND jobs.job_type = ANY($2::text[])
    ORDER BY jobs.run_at ASC, jobs.id ASC
    FOR UPDATE SKIP LOCKED
    LIMIT 1
)
UPDATE jobs
SET status = 'running',
    attempts = jobs.attempts + 1,
    claimed_at = NOW(),
    updated_at = NOW(),
    last_error = NULL
FROM next_job
WHERE jobs.id = next_job.id
RETURNING jobs.id, jobs.trace_id, jobs.job_type, jobs.status, jobs.payload, jobs.run_at, jobs.attempts, jobs.max_attempts, jobs.idempotency_key, jobs.last_error
`

type ClaimJobParams struct {
	RunAt   pgtype.Timestamptz
	Column2 []string
}

type ClaimJobRow struct {
	ID             int64
	TraceID        string
	JobType        string
	Status         string
	Payload        []byte
	RunAt          pgtype.Timestamptz
	Attempts       int32
	MaxAttempts    int32
	IdempotencyKey *string
	LastError      *string
}

func (q *Queries) ClaimJob(ctx context.Context, arg ClaimJobParams) (ClaimJobRow, error) {
	row := q.db.QueryRow(ctx, claimJob, arg.RunAt, arg.Column2)
	var i ClaimJobRow
	err := row.Scan(
		&i.ID,
		&i.TraceID,
		&i.JobType,
		&i.Status,
		&i.Payload,
		&i.RunAt,
		&i.Attempts,
		&i.MaxAttempts,
		&i.IdempotencyKey,
		&i.LastError,
	)
	return i, err
}

const enqueueJob = `-- name: EnqueueJob :execrows
INSERT INTO jobs (trace_id, job_type, status, idempotency_key, payload, run_at)
VALUES ($1, $2, 'queued', $3, $4, $5)
ON CONFLICT (idempotency_key) WHERE idempotency_key IS NOT NULL DO NOTHING
`

type EnqueueJobParams struct {
	TraceID        string
	JobType        string
	IdempotencyKey *string
	Payload        []byte
	RunAt          pgtype.Timestamptz
}

func (q *Queries) EnqueueJob(ctx context.Context, arg EnqueueJobParams) (int64, error) {
	result, err := q.db.Exec(ctx, enqueueJob,
		arg.TraceID,
		arg.JobType,
		arg.IdempotencyKey,
		arg.Payload,
		arg.RunAt,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const markJobDone = `-- name: MarkJobDone :exec
UPDATE jobs
SET status = 'done', completed_at = NOW(), updated_at = NOW()
WHERE id = $1
`

func (q *Queries) MarkJobDone(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, markJobDone, id)
	return err
}

const markJobRetry = `-- name: MarkJobRetry :exec
UPDATE jobs
SET status = CASE WHEN attempts >= max_attempts THEN 'failed' ELSE 'retry' END,
    run_at = $2,
    last_error = $3,
    updated_at = NOW()
WHERE id = $1
`

type MarkJobRetryParams struct {
	ID        int64
	RunAt     pgtype.Timestamptz
	LastError *string
}

func (q *Queries) MarkJobRetry(ctx context.Context, arg MarkJobRetryParams) error {
	_, err := q.db.Exec(ctx, markJobRetry, arg.ID, arg.RunAt, arg.LastError)
	return err
}
