// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package sqlcgen

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type AppClock struct {
	Singleton   bool
	OverrideNow pgtype.Timestamptz
	UpdatedAt   pgtype.Timestamptz
}

type DigestMessage struct {
	ID                int64
	UserID            int64
	TelegramMessageID int64
	State             string
	ProductIds        []byte
	CreatedAt         pgtype.Timestamptz
	UpdatedAt         pgtype.Timestamptz
}

type DraftSession struct {
	ID                  int64
	TraceID             string
	UserID              int64
	ChatID              int64
	SourceKind          string
	Status              string
	SourceMessageID     *int64
	DraftMessageID      *int64
	FeedbackMessageID   *int64
	DraftName           *string
	DraftExpiresOn      pgtype.Date
	RawDeadlinePhrase   *string
	DraftPayload        []byte
	CleanupAfter        pgtype.Timestamptz
	CreatedAt           pgtype.Timestamptz
	UpdatedAt           pgtype.Timestamptz
	ConfirmedProductID  *int64
	EditPromptMessageID *int64
}

type IngestEvent struct {
	ID          int64
	TraceID     string
	UserID      *int64
	ChatID      *int64
	MessageID   *int64
	MessageKind string
	Status      string
	Summary     *string
	Metadata    []byte
	CreatedAt   pgtype.Timestamptz
	UpdatedAt   pgtype.Timestamptz
}

type Job struct {
	ID             int64
	TraceID        string
	JobType        string
	Status         string
	IdempotencyKey *string
	Payload        []byte
	RunAt          pgtype.Timestamptz
	ClaimedAt      pgtype.Timestamptz
	CompletedAt    pgtype.Timestamptz
	Attempts       int32
	MaxAttempts    int32
	LastError      *string
	CreatedAt      pgtype.Timestamptz
	UpdatedAt      pgtype.Timestamptz
}

type Product struct {
	ID                int64
	UserID            int64
	Name              string
	NormalizedName    string
	ExpiresOn         pgtype.Date
	RawDeadlinePhrase *string
	Status            string
	SourceKind        string
	CreatedAt         pgtype.Timestamptz
	ClosedAt          pgtype.Timestamptz
}

type UserSetting struct {
	UserID             int64
	ChatID             int64
	Timezone           string
	DigestLocalTime    string
	DashboardMessageID *int64
	Active             bool
	CreatedAt          pgtype.Timestamptz
	UpdatedAt          pgtype.Timestamptz
}
