// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: products.sql

package sqlcgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const activeProductsExist = `-- name: ActiveProductsExist :one
SELECT EXISTS (
    SELECT 1
    FROM products
    WHERE id = ANY($1::bigint[])
      AND status = 'active'
)
`

func (q *Queries) ActiveProductsExist(ctx context.Context, dollar_1 []int64) (bool, error) {
	row := q.db.QueryRow(ctx, activeProductsExist, dollar_1)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const countActiveProducts = `-- name: CountActiveProducts :one
SELECT COUNT(*)::bigint
FROM products
WHERE user_id = $1 AND status = 'active'
`

func (q *Queries) CountActiveProducts(ctx context.Context, userID int64) (int64, error) {
	row := q.db.QueryRow(ctx, countActiveProducts, userID)
	var column_1 int64
	err := row.Scan(&column_1)
	return column_1, err
}

const countSoonProducts = `-- name: CountSoonProducts :one
SELECT COUNT(*)::bigint
FROM products
WHERE user_id = $1
  AND status = 'active'
  AND expires_on >= $2::date
  AND expires_on <= $3::date
`

type CountSoonProductsParams struct {
	UserID  int64
	Column2 pgtype.Date
	Column3 pgtype.Date
}

func (q *Queries) CountSoonProducts(ctx context.Context, arg CountSoonProductsParams) (int64, error) {
	row := q.db.QueryRow(ctx, countSoonProducts, arg.UserID, arg.Column2, arg.Column3)
	var column_1 int64
	err := row.Scan(&column_1)
	return column_1, err
}

const createProduct = `-- name: CreateProduct :one
INSERT INTO products (user_id, name, normalized_name, expires_on, raw_deadline_phrase, status, source_kind)
VALUES ($1, $2, $3, $4, $5, 'active', $6)
RETURNING id, user_id, name, normalized_name, expires_on, raw_deadline_phrase, status, source_kind, created_at, closed_at
`

type CreateProductParams struct {
	UserID            int64
	Name              string
	NormalizedName    string
	ExpiresOn         pgtype.Date
	RawDeadlinePhrase *string
	SourceKind        string
}

func (q *Queries) CreateProduct(ctx context.Context, arg CreateProductParams) (Product, error) {
	row := q.db.QueryRow(ctx, createProduct,
		arg.UserID,
		arg.Name,
		arg.NormalizedName,
		arg.ExpiresOn,
		arg.RawDeadlinePhrase,
		arg.SourceKind,
	)
	var i Product
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.NormalizedName,
		&i.ExpiresOn,
		&i.RawDeadlinePhrase,
		&i.Status,
		&i.SourceKind,
		&i.CreatedAt,
		&i.ClosedAt,
	)
	return i, err
}

const getProduct = `-- name: GetProduct :one
SELECT id, user_id, name, normalized_name, expires_on, raw_deadline_phrase, status, source_kind, created_at, closed_at
FROM products
WHERE id = $1
`

func (q *Queries) GetProduct(ctx context.Context, id int64) (Product, error) {
	row := q.db.QueryRow(ctx, getProduct, id)
	var i Product
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.NormalizedName,
		&i.ExpiresOn,
		&i.RawDeadlinePhrase,
		&i.Status,
		&i.SourceKind,
		&i.CreatedAt,
		&i.ClosedAt,
	)
	return i, err
}

const getProductByID = `-- name: GetProductByID :one
SELECT id, user_id, name, normalized_name, expires_on, raw_deadline_phrase, status, source_kind, created_at, closed_at
FROM products
WHERE id = $1
`

func (q *Queries) GetProductByID(ctx context.Context, id int64) (Product, error) {
	row := q.db.QueryRow(ctx, getProductByID, id)
	var i Product
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.NormalizedName,
		&i.ExpiresOn,
		&i.RawDeadlinePhrase,
		&i.Status,
		&i.SourceKind,
		&i.CreatedAt,
		&i.ClosedAt,
	)
	return i, err
}

const listActiveProducts = `-- name: ListActiveProducts :many
SELECT id, user_id, name, normalized_name, expires_on, raw_deadline_phrase, status, source_kind, created_at, closed_at
FROM products
WHERE user_id = $1 AND status = 'active'
ORDER BY expires_on ASC, id DESC
`

func (q *Queries) ListActiveProducts(ctx context.Context, userID int64) ([]Product, error) {
	rows, err := q.db.Query(ctx, listActiveProducts, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Product
	for rows.Next() {
		var i Product
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Name,
			&i.NormalizedName,
			&i.ExpiresOn,
			&i.RawDeadlinePhrase,
			&i.Status,
			&i.SourceKind,
			&i.CreatedAt,
			&i.ClosedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listActiveProductsPage = `-- name: ListActiveProductsPage :many
SELECT id, user_id, name, normalized_name, expires_on, raw_deadline_phrase, status, source_kind, created_at, closed_at
FROM products
WHERE user_id = $1 AND status = 'active'
ORDER BY expires_on ASC, id DESC
LIMIT $2 OFFSET $3
`

type ListActiveProductsPageParams struct {
	UserID int64
	Limit  int32
	Offset int32
}

func (q *Queries) ListActiveProductsPage(ctx context.Context, arg ListActiveProductsPageParams) ([]Product, error) {
	rows, err := q.db.Query(ctx, listActiveProductsPage, arg.UserID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Product
	for rows.Next() {
		var i Product
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Name,
			&i.NormalizedName,
			&i.ExpiresOn,
			&i.RawDeadlinePhrase,
			&i.Status,
			&i.SourceKind,
			&i.CreatedAt,
			&i.ClosedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listExpiredProducts = `-- name: ListExpiredProducts :many
SELECT id, user_id, name, normalized_name, expires_on, raw_deadline_phrase, status, source_kind, created_at, closed_at
FROM products
WHERE user_id = $1
  AND status = 'active'
  AND expires_on < $2::date
ORDER BY expires_on ASC, id DESC
`

type ListExpiredProductsParams struct {
	UserID  int64
	Column2 pgtype.Date
}

func (q *Queries) ListExpiredProducts(ctx context.Context, arg ListExpiredProductsParams) ([]Product, error) {
	rows, err := q.db.Query(ctx, listExpiredProducts, arg.UserID, arg.Column2)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Product
	for rows.Next() {
		var i Product
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Name,
			&i.NormalizedName,
			&i.ExpiresOn,
			&i.RawDeadlinePhrase,
			&i.Status,
			&i.SourceKind,
			&i.CreatedAt,
			&i.ClosedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSoonProducts = `-- name: ListSoonProducts :many
SELECT id, user_id, name, normalized_name, expires_on, raw_deadline_phrase, status, source_kind, created_at, closed_at
FROM products
WHERE user_id = $1
  AND status = 'active'
  AND expires_on >= $2::date
  AND expires_on <= $3::date
ORDER BY expires_on ASC, id DESC
`

type ListSoonProductsParams struct {
	UserID  int64
	Column2 pgtype.Date
	Column3 pgtype.Date
}

func (q *Queries) ListSoonProducts(ctx context.Context, arg ListSoonProductsParams) ([]Product, error) {
	rows, err := q.db.Query(ctx, listSoonProducts, arg.UserID, arg.Column2, arg.Column3)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Product
	for rows.Next() {
		var i Product
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Name,
			&i.NormalizedName,
			&i.ExpiresOn,
			&i.RawDeadlinePhrase,
			&i.Status,
			&i.SourceKind,
			&i.CreatedAt,
			&i.ClosedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSoonProductsPage = `-- name: ListSoonProductsPage :many
SELECT id, user_id, name, normalized_name, expires_on, raw_deadline_phrase, status, source_kind, created_at, closed_at
FROM products
WHERE user_id = $1
  AND status = 'active'
  AND expires_on >= $2::date
  AND expires_on <= $3::date
ORDER BY expires_on ASC, id DESC
LIMIT $4 OFFSET $5
`

type ListSoonProductsPageParams struct {
	UserID  int64
	Column2 pgtype.Date
	Column3 pgtype.Date
	Limit   int32
	Offset  int32
}

func (q *Queries) ListSoonProductsPage(ctx context.Context, arg ListSoonProductsPageParams) ([]Product, error) {
	rows, err := q.db.Query(ctx, listSoonProductsPage,
		arg.UserID,
		arg.Column2,
		arg.Column3,
		arg.Limit,
		arg.Offset,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Product
	for rows.Next() {
		var i Product
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Name,
			&i.NormalizedName,
			&i.ExpiresOn,
			&i.RawDeadlinePhrase,
			&i.Status,
			&i.SourceKind,
			&i.CreatedAt,
			&i.ClosedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateProductStatus = `-- name: UpdateProductStatus :exec
UPDATE products
SET status = $2,
    closed_at = CASE WHEN $2 = 'active' THEN NULL ELSE NOW() END
WHERE id = $1
`

type UpdateProductStatusParams struct {
	ID     int64
	Status string
}

func (q *Queries) UpdateProductStatus(ctx context.Context, arg UpdateProductStatusParams) error {
	_, err := q.db.Exec(ctx, updateProductStatus, arg.ID, arg.Status)
	return err
}
