// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: user_settings.sql

package sqlcgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const dashboardStats = `-- name: DashboardStats :one
SELECT
    COUNT(*) FILTER (WHERE status = 'active')::bigint AS active_count,
    COUNT(*) FILTER (WHERE status = 'active' AND expires_on >= $2::date AND expires_on <= $3::date)::bigint AS soon_count,
    COUNT(*) FILTER (WHERE status = 'active' AND expires_on < $2::date)::bigint AS expired_count,
    COUNT(*) FILTER (WHERE status = 'consumed')::bigint AS consumed_count,
    COUNT(*) FILTER (WHERE status = 'discarded')::bigint AS discarded_count,
    COUNT(*) FILTER (WHERE status = 'deleted')::bigint AS deleted_count
FROM products
WHERE user_id = $1
`

type DashboardStatsParams struct {
	UserID  int64
	Column2 pgtype.Date
	Column3 pgtype.Date
}

type DashboardStatsRow struct {
	ActiveCount    int64
	SoonCount      int64
	ExpiredCount   int64
	ConsumedCount  int64
	DiscardedCount int64
	DeletedCount   int64
}

func (q *Queries) DashboardStats(ctx context.Context, arg DashboardStatsParams) (DashboardStatsRow, error) {
	row := q.db.QueryRow(ctx, dashboardStats, arg.UserID, arg.Column2, arg.Column3)
	var i DashboardStatsRow
	err := row.Scan(
		&i.ActiveCount,
		&i.SoonCount,
		&i.ExpiredCount,
		&i.ConsumedCount,
		&i.DiscardedCount,
		&i.DeletedCount,
	)
	return i, err
}

const getUserSettings = `-- name: GetUserSettings :one
SELECT user_id, chat_id, timezone, digest_local_time, dashboard_message_id
FROM user_settings
WHERE user_id = $1
`

type GetUserSettingsRow struct {
	UserID             int64
	ChatID             int64
	Timezone           string
	DigestLocalTime    string
	DashboardMessageID *int64
}

func (q *Queries) GetUserSettings(ctx context.Context, userID int64) (GetUserSettingsRow, error) {
	row := q.db.QueryRow(ctx, getUserSettings, userID)
	var i GetUserSettingsRow
	err := row.Scan(
		&i.UserID,
		&i.ChatID,
		&i.Timezone,
		&i.DigestLocalTime,
		&i.DashboardMessageID,
	)
	return i, err
}

const listUsers = `-- name: ListUsers :many
SELECT user_id, chat_id, timezone, digest_local_time, dashboard_message_id
FROM user_settings
WHERE active = TRUE
ORDER BY user_id ASC
`

type ListUsersRow struct {
	UserID             int64
	ChatID             int64
	Timezone           string
	DigestLocalTime    string
	DashboardMessageID *int64
}

func (q *Queries) ListUsers(ctx context.Context) ([]ListUsersRow, error) {
	rows, err := q.db.Query(ctx, listUsers)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListUsersRow
	for rows.Next() {
		var i ListUsersRow
		if err := rows.Scan(
			&i.UserID,
			&i.ChatID,
			&i.Timezone,
			&i.DigestLocalTime,
			&i.DashboardMessageID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setDashboardMessageID = `-- name: SetDashboardMessageID :exec
UPDATE user_settings
SET dashboard_message_id = $2,
    updated_at = NOW()
WHERE user_id = $1
`

type SetDashboardMessageIDParams struct {
	UserID             int64
	DashboardMessageID *int64
}

func (q *Queries) SetDashboardMessageID(ctx context.Context, arg SetDashboardMessageIDParams) error {
	_, err := q.db.Exec(ctx, setDashboardMessageID, arg.UserID, arg.DashboardMessageID)
	return err
}

const updateUserDigestLocalTime = `-- name: UpdateUserDigestLocalTime :exec
UPDATE user_settings
SET digest_local_time = $2, updated_at = NOW()
WHERE user_id = $1
`

type UpdateUserDigestLocalTimeParams struct {
	UserID          int64
	DigestLocalTime string
}

func (q *Queries) UpdateUserDigestLocalTime(ctx context.Context, arg UpdateUserDigestLocalTimeParams) error {
	_, err := q.db.Exec(ctx, updateUserDigestLocalTime, arg.UserID, arg.DigestLocalTime)
	return err
}

const updateUserTimezone = `-- name: UpdateUserTimezone :exec
UPDATE user_settings
SET timezone = $2, updated_at = NOW()
WHERE user_id = $1
`

type UpdateUserTimezoneParams struct {
	UserID   int64
	Timezone string
}

func (q *Queries) UpdateUserTimezone(ctx context.Context, arg UpdateUserTimezoneParams) error {
	_, err := q.db.Exec(ctx, updateUserTimezone, arg.UserID, arg.Timezone)
	return err
}

const upsertUserSettings = `-- name: UpsertUserSettings :execrows
INSERT INTO user_settings (
    user_id,
    chat_id,
    timezone,
    digest_local_time,
    dashboard_message_id
)
VALUES ($1, $2, $3, $4, $5)
ON CONFLICT (user_id) DO UPDATE SET
    chat_id = EXCLUDED.chat_id,
    timezone = EXCLUDED.timezone,
    digest_local_time = EXCLUDED.digest_local_time,
    dashboard_message_id = COALESCE(EXCLUDED.dashboard_message_id, user_settings.dashboard_message_id),
    updated_at = NOW()
`

type UpsertUserSettingsParams struct {
	UserID             int64
	ChatID             int64
	Timezone           string
	DigestLocalTime    string
	DashboardMessageID *int64
}

func (q *Queries) UpsertUserSettings(ctx context.Context, arg UpsertUserSettingsParams) (int64, error) {
	result, err := q.db.Exec(ctx, upsertUserSettings,
		arg.UserID,
		arg.ChatID,
		arg.Timezone,
		arg.DigestLocalTime,
		arg.DashboardMessageID,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
